import { useEffect, useState } from 'react'
import { useLocation, Link } from 'react-router-dom'
import { X, Info } from 'lucide-react'

export function PreviewBanner() {
  const location = useLocation()
  const [closed, setClosed] = useState(false)

  useEffect(() => {
    setClosed(false)
  }, [location.pathname])

  if (closed) return null

  return (
    <div className="fixed right-4 top-4 z-50 w-80 rounded-2xl border border-warning/30 bg-warning/10 p-4 shadow-card">
      <div className="flex gap-3">
        <Info className="h-5 w-5 shrink-0 text-warning" />
        <div className="min-w-0 text-sm text-warning">
          <p className="font-bold">Preview only</p>
          <p className="mt-1 leading-relaxed">
            This is a simulated client-side preview. Data stays in your browser and answers are generated by an LLM.
            For the real demo, see the <Link to="/demo" className="underline hover:text-amber-700">video, docs and PPT</Link>.
          </p>
        </div>
        <button
          type="button"
          onClick={() => setClosed(true)}
          className="shrink-0 rounded-full p-1 text-warning hover:bg-warning/20"
          aria-label="Close preview notice"
        >
          <X className="h-4 w-4" />
        </button>
      </div>
    </div>
  )
}